sonar.projectKey=Heretek-AI_heretek-manager
sonar.organization=heretek-ai
sonar.projectName=heretek-manager
sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info


sonar.sourceEncoding=UTF-8
